# Generated by Django 5.0.6 on 2024-06-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblog',
            name='Matric_number',
            field=models.CharField(max_length=20),
        ),
    ]
